
name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: dependencies
      run: sudo apt-get install build-essential libtool autotools-dev autoconf pkg-config libssl-dev libevent-dev -y && sudo apt install libssl1.0-dev -y && sudo apt-get install libboost-all-dev -y && sudo add-apt-repository ppa:bitcoin/bitcoin && sudo apt update && sudo apt-get install libdb4.8-dev libdb4.8++-dev -y
    - name: autogen
      run: sudo ./autogen.sh
    - name: configure
      run: sudo ./configure --disable-test --disable-bench
    - name: make
      run: sudo make
